### ISSUE TITLE
How to read from GetRawInputDeviceList ?

### ISSUE THREAD

**Issue by yadomi** [jeet-parekh/winapi#1]
Hello, 

I'm trying to use `GetRawInputDeviceList` to return the list of current connected input devices but I can't get that function work. 

Here is what i'm trying to do:

```go
func main() {
	var (
		rid                 winapi.RAWINPUTDEVICELIST
		cbSize              = unsafe.Sizeof(rid)
		pRawInputDeviceList []winapi.RAWINPUTDEVICELIST
		puiNumDevices       *uintptr
	)

	winapi.GetRawInputDeviceList(pRawInputDeviceList, puiNumDevices, cbSize)
	fmt.Printf("%v %v", pRawInputDeviceList, puiNumDevices)
}
```

But `pRawInputDeviceList` is still empty and `puiNumDevices` is `nil` and don't understand what am I doing wrong.

Any advise or guidance would be greatly appreciated :)

**Comment by jeet-parekh** [comment]
Hey,

What you're trying to do, I would do it in two steps. First get the number of devices, and then get the devices themselves.

```go
func main() {
	rid := winapi.RAWINPUTDEVICELIST{}
	cbSize := unsafe.Sizeof(rid)
	var puiNumDevices uintptr

	// this would set the number of attached devices to puiNumDevices
	winapi.GetRawInputDeviceList(nil, &puiNumDevices, cbSize)

	// now create a slice of RAWINPUTDEVICELIST with the appropriate size
	pRawInputDeviceList := make([]winapi.RAWINPUTDEVICELIST, puiNumDevices)

	// this would get the attached devices to pRawInputDeviceList
	winapi.GetRawInputDeviceList(pRawInputDeviceList, &puiNumDevices, cbSize)
}
```

To get the number of devices, you need to pass `nil` instead of a slice of `RAWINPUTDEVICELIST`.

Hope that helps.
